# file: .github/workflows/ci-app.yml
name: ci-app
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v3
      - run: make setup
      # Запускаем линтер
      - name: run lint  
        run: make lint
      # Запускаем тесты
      - name: run tests
        run: make test

